name: Build and Archive

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Compress windows
        run: zip -r window.zip ./windows/

      - name: Compress linux
        run: zip -r linux.zip ./linux/

      - name: Upload windows artifact
        uses: actions/upload-artifact@v4
        with:
          name: windows
          path: windows.zip

      - name: Upload linux artifact
        uses: actions/upload-artifact@v4
        with:
          name: linux
          path: linux.zip
      # 在 workflow 文件末尾添加这个步骤
      - name: Upload to Release
        if: startsWith(github.ref, 'refs/tags/')  # 只有 tag 触发才执行
        uses: softprops/action-gh-release@v1
        with:
          files: |
            linux.zip
            windows.zip
          generate_release_notes: true  # 自动生成 Release 说明
          fail_on_unmatched_files: false  # 如果某个文件不存在也不报错