name: Build and Archive

on:
  push:
    branches:
      - main        # 当推送到 main 分支时触发
      - develop                # 只有打 tag 时才触发完整发布
  workflow_dispatch:    # 支持手动触发

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
       
      - name: checkout
        uses: actions/checkout@v4
      - name: show dir 
        run: ls -al 
      # 上传到 Artifacts（工作流产物）
      - name: Upload windows artifact
        uses: actions/upload-artifact@v7
        with:
          name: windows
          path: windows/
          archive: true
          include-hidden-files: true
      - name: Upload linux artifact
        uses: actions/upload-artifact@v7
        with:
          name: linux
          path: linux/
          archive: true
          include-hidden-files: true